<div class="navigation" id="sub-nav">

			<ul class="tabbed">
				<li class="current-tab"><a href="/Home"></a></li>
				<li><a href="/Home/about-us"></a></li>
				<li><a href="/Home/membership"></a></li>
                     		<li id="po"><a href="/Home/news"> </a></li>
                                <li id="po"><a href="/Home/testi"> </a></li>
                       </ul>
   
	 
<div class="clearer">&nbsp;</div>

			

		</div>
                                 
	</div>

	<div id="splash">

		<div class="col3 left">
			
			<h2 class="label label-green">Notre mission</h2>

			<p class="quiet large">Ce que nous voulons atteindre</p>

			<p> Notre mission est de vous trouver l’appartement qui vous correspond, que cela soit pour quelques jours, quelques
			semaines ou quelques mois et de vous mettre en relation avec le propriétaire qui se fera un plaisir 
			de vous accueillir pour faire de votre séjour parisien une expérience inoubliable.</p>
    
			

		</div>

		<div class="col3-mid left">
			
			<h2 class="label label-orange">Les dernières nouvelles </h2>

                           <marquee> 
                   <a href="#">  <img src="<?php echo $this->baseUrl();?>/img/apt_1.jpg"  width="170" height="170" /></a>

			<a href="#">	<img src="<?php echo $this->baseUrl();?>/img/apt_2.jpg" width="300" height="170" />
			</a>
                          <a href="#" >
				<img src="<?php echo $this->baseUrl();?>/img/apt_3.jpg" width="300" height="170" />
			</a>
                        <a href="#" >
				<img src="<?php echo $this->baseUrl();?>/img/apt_4.jpg" width="300" height="170" />
			</a>
      
                          </marquee> 
                                     <p><a href="/Home/news/" class="more"> Voir plus ... &raquo;</a></p>       
		</div>

		<div class="col3 right">
			
			<h2 class="label label-blue"> Suivez-nous </h2>
			<p><img src="<?php echo $this->baseUrl();?>/img/twitter.png" width="40" height="30" /> http://twitter.com/Anass</p>
			<p><img src="<?php echo $this->baseUrl();?>/img/facebook.png" width="40" height="30"/> http://www.facebook.com/siham</p>
			<p><img src="<?php echo $this->baseUrl();?>/img/email.png" width="40" height="30"/> Siham@Anass.com</p>
			<p><img src="<?php echo $this->baseUrl();?>/img/googleplus.png" width="40" height="30"/> http://www.google.com/khamkham_fashion</p>

		</div>

		<div class="clearer">&nbsp;</div>

	</div>

	<div class="main" id="main-two-columns">

		<div class="left" id="main-content">

			<div class="section">

				<div class="section-title"> Appartement </div>

				<div class="section-content">

					<div class="post">

					<canvas id="monCanvas" data-processing-sources="image_web\image_web.pde"></canvas>
					</div>

					<div class="content-separator"></div>

					<div class="col3 left">
						<div class="column-content">

							<div class="post">
      
							</div>

						</div>
					</div>

					<div class="col3 col3-mid left">
						<div class="column-content">

							<div class="post">
								
							</div>

						</div>
					</div>

					<div class="col3 right">
						<div class="column-content">

							<div class="post">
								
							</div>

						</div>
					</div>

					<div class="clearer">&nbsp;</div>

				</div>

			</div>

			<div class="clearer">&nbsp;</div>
			
		</div>

		<div class="right sidebar" id="sidebar">

			<div class="section">

				<div class="section-title">Search  </div>
<div class="section-content">
					<form method="GET" action="http://www.google.com/search">
                                         <input type="hidden" NAME="sitesearch" value>  
						<input type="text" NAME="q" class="text" size="28" /> &nbsp; <input type="submit" class="button" Name="sa"value="Submit" />
					</form>
				</div>

			</div>

			

			<div class="section">

				<div class="section-title"> Temoignages </div>

				<div class="section-content">

					<ul class="nice-list">
						<li><a href="#">Gabriel Penaloza</a> <span class="quiet">- Tech Manager</span></li>
						<li><a href="#">Danilo Malatesta</a> <span class="quiet">- Entrepreneur</span></li>
						<li><a href="#">Eve Riboud</a> <span class="quiet">- CEO</span></li>
						<li><a href="#">Alexey Kurbatov</a> <span class="quiet">- Developer</span></li>
						<li><a href="#">Khalid Hadj</a> <span class="quiet">- Salesman</span></li>
					</ul>
					
				</div>

			</div></div>

			

		<div class="clearer">&nbsp;</div>

	</div>